### ISSUE TITLE
Invalid default_error_message in EnumField

### ISSUE THREAD

**Issue by kevin-brown** [seebass/drf-enum-field#1]
This was reported by @Tim-Erwin over at https://github.com/tomchristie/django-rest-framework/issues/3247

> When I make a POST on a viewset with a model that has an EnumField and I use an invalid value for that field, I get the error message
> 
> > 'tuple' object has no attribute 'format'
> 
> The reasons seems to be in fields.py:
> 
> ``` python
> default_error_messages = {
>     'invalid': ("No matching enum type.",)
> }
> ```
> 
> It should be not be a tuple but a simple or translated string.

The issue occurs because of [this line](https://github.com/seebass/drf-enum-field/blob/89a54c8b05da5b65f045373841d7a9e55c469f90/drf_enum_field/fields.py#L6).

**Comment by belugame** [comment]
I made a fix for it in a fork but I don't have the time to ensure it does not break anything else:
https://github.com/belugame/drf-enum-field

**Comment by Archelyst** [comment]
Would you mind creating a PR?

**Comment by belugame** [comment]
done

**Comment by Archelyst** [comment]
Awesome, thanks

**Comment by Jesse-jApps** [comment]
Unfortunately the problem still remains!
