### ISSUE TITLE
EnumField default_error_messages looks wrong

### ISSUE THREAD

**Issue by souliane** [seebass/drf-enum-field#6]
It defines a tuple:

```
    default_error_messages = {
        'invalid': ("No matching enum type.",)
    }
```

Should be a string instead (without the comma):

```
    default_error_messages = {
        'invalid': ("No matching enum type.")
    }
```

Otherwise we will get "AttributeError: 'tuple' object has no attribute 'format'" when calling self.fail('invalid') .

**Comment by seebass** [comment]
fixed in v0.9.2
